// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cykrxphdqtqleawrmaea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5a3J4cGhkcXRxbGVhd3JtYWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mjk3NDQsImV4cCI6MjA2NDQwNTc0NH0.p5Un3HGta1-gIJqN7pmeBPWFPyEvWRTalaNT1_UIp60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);